import Head from "next/head";
import HomeComponent from "@/components/Home";

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Drive Clone lite</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#bcb7c2c9] to-[#f0e5ffc9]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[3rem]">
          Seja Bem Vindo <span className="text-[hsl(229,18%,47%)]">{session?.user.name}</span>
          </h1> */}
          <HomeComponent />


        </div>
      </main>
    </>
  );
}
